# Generated by Django 4.0.4 on 2022-06-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nro de fase en numeros romanos', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del personaje', max_length=30)),
                ('superpoder', models.CharField(help_text='Ingrese el superpoder del personaje', max_length=30)),
                ('actor_apellido', models.CharField(help_text='Ingrese el apellido del actor', max_length=30)),
                ('actor_nombre', models.CharField(help_text='Ingrese el nombre del actor', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la película', max_length=40)),
                ('sinopsis', models.TextField(help_text='Ingrese el resumen de la película')),
                ('anio', models.IntegerField(help_text='Ingrese el año de estreno  de la película')),
                ('duracion', models.IntegerField(help_text='Ingrese la duración en minutos de la película')),
                ('nombre_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.fases')),
            ],
        ),
    ]
