# Generated by Django 4.0.4 on 2022-06-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes_Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.peliculas')),
                ('nombre_personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.personajes')),
            ],
        ),
    ]
