# Generated by Django 4.0.5 on 2022-06-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelApp', '0002_personajes_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='nombre_fase',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='personajes_pelicula',
            name='nombre_pelicula',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personajes_pelicula',
            name='nombre_personaje',
            field=models.CharField(max_length=30),
        ),
    ]
